//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMarket.Infrastructure.SqlScripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderSqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderSqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineMarket.Infrastructure.SqlScripts.OrderSqlScripts", typeof(OrderSqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            INSERT INTO &quot;OrderProducts&quot; (&quot;OrderId&quot;, &quot;ProductId&quot;, &quot;Amount&quot;, &quot;TotalPrice&quot;)
        ///            VALUES (@OrderId, @ProductId, @Amount, @TotalPrice)
        ///        .
        /// </summary>
        internal static string AddProductToOrder {
            get {
                return ResourceManager.GetString("AddProductToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            INSERT INTO &quot;Orders&quot; (&quot;CustomerFullName&quot;, &quot;CustomerPhone&quot;, &quot;CreatedAt&quot;)
        ///            VALUES (@CustomerFullName, @CustomerPhone, @CreatedAt)
        ///            RETURNING &quot;Id&quot;
        ///        .
        /// </summary>
        internal static string CreateOrder {
            get {
                return ResourceManager.GetString("CreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            SELECT o.&quot;Id&quot;, o.&quot;CreatedAt&quot;, o.&quot;CustomerFullName&quot;, o.&quot;CustomerPhone&quot;,
        ///                SUM(op.&quot;Amount&quot; * p.&quot;Price&quot;) OVER (PARTITION BY o.&quot;Id&quot;) as &quot;TotalPrice&quot;,
        ///                op.&quot;ProductId&quot;, p.&quot;Name&quot; as &quot;ProductName&quot;, op.&quot;Amount&quot; as &quot;ProductAmount&quot;
        ///            FROM &quot;Orders&quot; o
        ///            LEFT JOIN &quot;OrderProducts&quot; op ON o.&quot;Id&quot; = op.&quot;OrderId&quot;
        ///            LEFT JOIN &quot;Products&quot; p ON op.&quot;ProductId&quot; = p.&quot;Id&quot;
        ///            ORDER BY o.&quot;Id&quot;
        ///        .
        /// </summary>
        internal static string GetAllOrders {
            get {
                return ResourceManager.GetString("GetAllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            SELECT o.&quot;Id&quot;, o.&quot;CreatedAt&quot;, o.&quot;CustomerFullName&quot;, o.&quot;CustomerPhone&quot;,
        ///                SUM(op.&quot;Amount&quot; * p.&quot;Price&quot;) OVER (PARTITION BY o.&quot;Id&quot;) AS &quot;TotalPrice&quot;,
        ///                op.&quot;ProductId&quot;, p.&quot;Name&quot; AS &quot;ProductName&quot;, op.&quot;Amount&quot; AS &quot;ProductAmount&quot;
        ///            FROM &quot;Orders&quot; o
        ///            LEFT JOIN &quot;OrderProducts&quot; op ON o.&quot;Id&quot; = op.&quot;OrderId&quot;
        ///            LEFT JOIN &quot;Products&quot; p ON op.&quot;ProductId&quot; = p.&quot;Id&quot;
        ///            WHERE o.&quot;Id&quot; = @Id
        ///            ORDER BY o.&quot;Id&quot;
        ///        .
        /// </summary>
        internal static string GetOrderById {
            get {
                return ResourceManager.GetString("GetOrderById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            SELECT p.&quot;Price&quot; * @Amount as TotalPrice
        ///            FROM &quot;Products&quot; p
        ///            WHERE p.&quot;Id&quot; = @ProductId
        ///        .
        /// </summary>
        internal static string GetTotalPrice {
            get {
                return ResourceManager.GetString("GetTotalPrice", resourceCulture);
            }
        }
    }
}
